steps:
  -
    name: "🔨"
    command: "scripts/tests.sh"
    plugins:
      - ssh://git@github.com/buildkite/plugins/docker-compose:
          container: "agent"

  -
    name: "📦"
    command: "scripts/build-binaries.sh"
    artifact_paths: "pkg/*"
    plugins:
      - ssh://git@github.com/buildkite/plugins/docker-compose:
          container: "agent"

  - wait

  -
    name: ":redhat: experimental"
    command: "scripts/rpm-package.sh"
    artifact_paths: "rpm/**/*"
    branches: "master"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"

  -
    name: ":debian: experimental"
    command: "scripts/debian-package.sh"
    artifact_paths: "deb/**/*"
    branches: "master"
    env:
      CODENAME: "experimental"
    agents:
      queue: "deploy"

  -
    name: ":github: :hammer:"
    command: "scripts/build-github-release.sh"
    artifact_paths: "releases/**/*"
    branches: "master"
    plugins:
      - ssh://git@github.com/buildkite/plugins/docker-compose:
          container: "agent"

  - block: ":shipit: Unstable"

  -
    name: ":octocat: :rocket:"
    command: "scripts/github-release.sh"
    branches: "master"
    agents:
      queue: "deploy"

  -
    name: ":redhat:"
    command: "scripts/rpm-package.sh"
    artifact_paths: "rpm/**/*"
    branches: "master"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  -
    name: ":debian:"
    command: "scripts/debian-package.sh"
    branches: "master"
    env:
      CODENAME: "unstable"
    agents:
      queue: "deploy"

  - wait

  -
    name: ":whale:"
    command: "scripts/release-docker.sh"
    branches: "master"
    agents:
      queue: "deploy"

  -
    name: ":beer:"
    command: "scripts/release-homebrew.sh"
    artifact_paths: "pkg/*.rb;pkg/*.json"
    branches: "master"
    agents:
      queue: "deploy"

  - block: ":shipit: Stable"

  -
    name: ":redhat:"
    command: "scripts/rpm-package.sh"
    artifact_paths: "rpm/**/*"
    branches: "master"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"

  -
    name: ":debian:"
    command: "scripts/debian-package.sh"
    branches: "master"
    env:
      CODENAME: "stable"
    agents:
      queue: "deploy"
